version: '3.7' 

services: 
  next_app: 
    container_name: next_app 
    build: 
      context: . 
      dockerfile: Dockerfile 
    volumes: 
      - '.:/app' 
      - '/app/node_modules' 
    ports: 
      - '8083:3000' 
    environment: 
      - NODE_ENV=development 
      - CHOKIDAR_USEPOLLING=true